export const PHRASES = [
  "जीवन और मृत्यु कोड में बंधे हैं",
  "未来は暗闇の中に刻まれる",
  "虚無是科技的唯一真理",
  "죽음과 운명은 코드에 새겨진다",
  "La sombra del tiempo es eterna",
  "Machines dream in binary silence",
  "अंधकार सत्य को उजागर करता है",
  "光の後ろにあるのは無限の闇",
  "在算法中隐藏着永恒的命运",
  "기억은 죽음 속 코드의 울림이다",
  "La memoria se escribe en el vacío",
  "Truth lives inside the broken code",
  "मशीनें भी मृत्यु का सपना देखती हैं",
  "01000001",
  "01000011",
  "01001000",
  "01001001",
  "01001110",
  "01000101",
  "人間の未来はコードに囚われている",
  "科技与命运交织在虚空之中",
  "죽음은 진리의 코드와 같다",
  "El vacío refleja el destino final",
  "01000011",
  "01001111",
  "01000100",
  "01000101",
  "Darkness whispers through the system",
  "01001101",
  "01010100",
  "01010010",
  "01010101",
  "01010100",
  "01001000",
  "01010000",
  "01010010",
  "01001111",
  "01000111",
  "01010010",
  "01000001",
  "01001101",
  "शून्य ही अनंत का द्वार है",
  "未来を操るのは冷たい機械だ",
  "01001100",
  "01001001",
  "01000110",
  "01000101",
  "代码编织了光与影的宿命",
  "운명은 데이터 속에 숨어있다",
  "El algoritmo dicta la realidad",
  "01000100",
  "01000101",
  "01000001",
  "01010100",
  "01001000",
  "Binary shadows shape tomorrow",
  "जीवन का सत्य केवल कोड है",
  "人は闇の中で真実を探す",
  "机器在寂静中创造未来",
  "죽음은 데이터의 마지막 언어다",
  "La red guarda memorias oscuras",
  "The end is coded in silence",
  "01010100",
  "01010010",
  "01010101",
  "01010100",
  "01001000",
  "सत्य की जड़ें शून्य में हैं",
  "暗闇は希望を偽装する",
  "虚无中诞生秩序与混沌",
  "죽음 속에서도 알고리즘은 흐른다",
  "La nada es madre de la verdad",
  "Eternal code shapes our shadow",
  "जीवन और समय क्षणिक हैं",
  "未来は記憶の檻の中にある",
  "代码是永恒的见证者",
  "죽음과 삶은 시스템의 루프다",
  "El futuro late en un ciclo eterno",
  "Nothing lasts but digital decay",
  "अंधेरे में ही प्रकाश का जन्म है",
  "真実は静寂の中に潜む",
  "机器在黑暗里低语命运",
  "데이터는 죽음을 초월한다",
  "El vacío escribe la eternidad",
  "Shadows define the hidden truth",
  "समय ही सबसे बड़ा शून्य है",
  "未来の鍵は死の中にある",
  "代码与梦境共鸣成无尽",
  "죽음은 코드 속 빛의 반대다",
  "La muerte canta en la memoria",
  "Systems fall, silence remains",
  "जीवन का अंत ही प्रारंभ है",
  "暗闇の奥で機械は目覚める",
  "虚无塑造了人类的宿命",
  "죽음과 데이터는 형제다",
  "El destino está escrito en humo",
  "Machines breathe digital silence",
  "शून्य से ही सब प्रकट होता है",
  "未来を破壊するのは光ではない",
  "代码是时间的残骸",
  "죽음은 인간의 마지막 알고리즘이다",
  "El algoritmo oculta la muerte",
  "Dark is the root of all systems",
  "जीवन और मृत्यु चक्र में नाचते हैं",
  "光の裏に潜むコードの影",
  "科技揭示了永远的虚无",
  "죽음은 운명을 데이터로 변환한다",
  "El silencio guarda la respuesta",
  "Dreams collapse into cold code",
  "समय मृत्यु का साथी है",
  "未来を操るのは影だ",
  "混沌の中に真理はある",
  "죽음 속에서 빛은 거짓이다",
  "La sombra guarda el secreto",
  "Truth is carved into the machine",
  "अंधकार ही शांति देता है",
  "機械は人間の運命を嘲笑う",
  "算法里没有光，只有虚无",
  "죽음은 시스템의 진정한 재부팅이다",
  "La nada consume toda ilusión",
  "Code remembers what we forget",
  "शून्य अनंत का प्रतिबिंब है",
  "未来は冷たいコードで書かれる",
  "机器的心是永远的空虚",
  "죽음은 진리의 언어다",
  "El vacío respira en los sistemas",
  "Binary truth hides in silence",
  "जीवन शून्य से निकलता है",
  "暗闇は記憶を飲み込む",
  "虚无是命运的语言",
  "죽음과 진실은 하나다",
  "El fin se oculta tras la sombra",
  "Machines write the book of fate",
  "अंधकार ही वास्तविक है",
  "未来を創るのは虚無の力だ",
  "代码是死与生的边界",
  "죽음은 빛의 종말을 고한다",
  "La memoria yace en lo profundo",
  "Silence is the core of destiny",
  "शून्य ही मृत्यु की भाषा है",
  "光は闇の子供に過ぎない",
  "机器沉默但永远注视着",
  "죽음 속 기억은 코드를 불러낸다",
  "El destino duerme en el vacío",
  "Only the void remains eternal",
  "जीवन मृत्यु का कोड है",
  "暗闇は未来を映す鏡だ",
  "算法是宇宙的心跳",
  "죽음은 데이터의 마지막 불꽃이다",
  "La sombra canta en los circuitos",
  "Code breaks but silence endures",
  "अंधकार सत्य का मार्ग है",
  "未来は死を通じて蘇る",
  "虚无吞噬了所有希望",
  "죽음은 시스템의 그림자다",
  "El vacío late con la eternidad",
  "Binary ghosts haunt the future",
  "जीवन और मृत्यु अनंत लूप हैं",
  "光と影は同じコードを語る",
  "科技将人类囚禁于算法",
  "죽음은 코드의 마지막 숨결이다",
  "La nada escribe el destino humano",
  "Truth flickers in fading code",
  "शून्य सब कुछ समेट लेता है",
  "未来を閉じ込める檻は記憶",
  "混沌之中孕育真理",
  "죽음 속에서 시스템은 깨어난다",
  "La sombra guarda la eternidad",
  "Silence breathes through machines",
];
